In [1]:
class Calculate_Date:
    def __init__(self, table_name):
        self.table_name = table_name
        print("DATE TABLE")
        print("----")
        print("Please select the date calculation you want from range")
        while True:
            calculated_date = input("Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION: ")
            if calculated_date not in ["1", "2", "3", "4", "5", "6", "7", "8"]:
                print("----")
                print("please select from range")
            else:
                break

        if calculated_date == "1":
            self.Year_Cal()
        elif calculated_date == "2":
            self.Quarter_Cal()
        elif calculated_date == "3":
            self.Month_Cal()
        elif calculated_date == "4":
            self.Week_Cal()
        elif calculated_date == "5":
            self.Day_Cal()
        elif calculated_date == "6":
            self.DateDiff_Cal()
        elif calculated_date == "7":
            self.DateAdd_Cal()
        else:
            print("Date Calculation Terminated")
            return

    def Year_Cal(self):
        print("\n")
        print("YEAR CALCULATION")
        print("----")
        try: 
            date_col = input("please enter the date column you want to extract year from; ⇛ SELECTION: ")
            new_col = input("please enter the new column name; ⇛ SELECTION: ")
            self.table_name[new_col] = self.table_name[date_col].dt.year
            print(f"Column: {new_col} is added")
        except Exception as exe:
            print("Invalid Date Column or Table Name")
            print("Error:", exe)
            return

    def Quarter_Cal(self):
        print("\n")
        print("QUARTER CALCULATION")
        print("----")
        print("please select what type of quarter calculation you want to perform")
        while True:
            type_of_quarter_cal = input("Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION: ")
            if type_of_quarter_cal not in ["1", "2", "3"]:
                print("This is not the range for quarter calculation")
            else:
                break
        
        if type_of_quarter_cal == "1":
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract quarter from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col].dt.quarter
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        
        elif type_of_quarter_cal == "2":
            print(" ")
            print("please enter the type of start of quarter you want to calculate")
            while True:
                try:
                    type_of_start_of_quarter = int(input("Start of Current Quarter: 0, Start of Next Quarter: 1, Start of Previous Quarter: -1; ⇛ SELECTION: "))
                    if type_of_start_of_quarter not in [0, 1, -1]:
                        print("please select from the range")
                    else:
                        break
                except Exception as exe:
                    print("This is an invalid input")
                    print("Error:", exe)
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract start of quarter from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = (self.table_name[date_col].dt.to_period("Q") + (type_of_start_of_quarter)).dt.start_time
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        else:
            print(" ")
            print("please enter the type of end of quarter you want to calculate")
            while True:
                try:
                    type_of_end_of_quarter = int(input("end of current quater: 0, end of next quarter: 1, end of previous quarter: -1; ⇛ SELECTION: "))
                    if type_of_end_of_quarter not in [0, 1, -1]:
                        print("please select from the range")
                    else:
                        break
                except Exception as exe:
                    print("Error:", exe)
                    print("this is an invalid input")
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract end of quarter from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = (self.table_name[date_col].dt.to_period("Q") + (type_of_end_of_quarter)).dt.end_time.dt.date
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return

    def Month_Cal(self):
        print("\n")
        print("MONTH CALCULATION")
        print("----")
        print("please select the type of month calculation you want perform")
        while True:
            type_of_month_cal = input("Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION: ")
            if type_of_month_cal not in ["1", "2", "3", "4"]:
                print("This is not the range for month calculation")
            else:
                break
        if type_of_month_cal == "1":
            print(" ")
            print("please select from range what month calculation you want")
            while True:
                month = input("Month Number(eg. 01): 1, Month Name abbv.(eg. Jan): 2, Month Name full(eg. January): 3; ⇛ SELECTION: ")
                if month not in ["1", "2", "3"]:
                    print("Invalid Selection Range")
                else:
                    break

            if month == "1":
                print(" ")
                try:
                    date_col = input("please enter the date column you want to extract month number from; ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = self.table_name[date_col].dt.month
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
                    
            elif month == "2":
                print(" ")
                try:
                    date_col = input("please enter the date column you want to extract month name abbv. from; ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = self.table_name[date_col].dt.strftime("%b")
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Error:", exe)
                    print("Invalid Date Column or Table Name")
                    return
            else:
                print(" ")
                try:
                    date_col = input("please enter the date column you want to extract month name full from; ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = self.table_name[date_col].dt.month_name()
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Error:", exe)
                    print("Invalid Date Column or Table Name")
                    return

        elif type_of_month_cal == "2":
            print(" ")
            print("please select from range what month year calculation you want")
            while True:
                type_month_year = input("month year abbv. (eg. jan-2025): 1, month year full (eg. January-2025): 2; ⇛ SELECTION: ")
                if type_month_year not in ["1", "2"]:
                    print("please select from range")
                else:
                    break
            if type_month_year == "1":
                print(" ")
                try:
                    date_col = input("please enter the date column you want to extract month year abbv. from; ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = self.table_name[date_col].dt.strftime("%b-%Y")
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
            else:
                print(" ")
                try:
                    date_col = input("please enter the date column you want to extract month year full from; ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = self.table_name[date_col].dt.strftime("%B-%Y")
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return

        elif type_of_month_cal == "3":
            print(" ")
            print("please select what start of month calculated column you want")
            while True:
                try:
                    start_of_month_type = int(input("Start of Current Month: 0, Start of Next Month: 1, Start of Previous Month: -1; ⇛ SELECTION: "))
                    if start_of_month_type not in [0, 1, -1]:
                        print("This is not a valid selection range")
                    else:
                        break
                except Exception as exe:
                    print("This is an invalid input")
                    print("Error:", exe)
                    
            print(" ")        
            try:
                date_col = input("please enter the date column you want to extract start of month from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = (self.table_name[date_col].dt.to_period("M") + (start_of_month_type)).dt.start_time
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        else:
            print(" ")
            print("please select what end of month calculated column you want")
            while True:
                try:
                    end_of_month_type = int(input("End of Current Month: 0, End of Next Month: 1, End of Previous Month: -1; ⇛ SELECTION: "))
                    if end_of_month_type not in [0, 1, -1]:
                        print("This is not a valid selection range")
                    else:
                        break
                except Exception as exe:
                    print("This is an invalid input")
                    print("Error:", exe)

            print(" ")
            try:
                date_col = input("please enter the date column you want to extract end of month from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = (self.table_name[date_col].dt.to_period("M") + (end_of_month_type)).dt.end_time.dt.date
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return

    def Week_Cal(self):
        print("\n")
        print("WEEK CALCULATION")
        print("----")
        print("please select the type of week calculation you want perform")
        while True:
            type_of_week_cal = input("Week Number(eg. 52): 1, WeekDay Number(eg. 3) : 2, WeekDay Name abbv.(eg. wed): 3, WeekDay Name full.(eg. wednesday): 4; ⇛ SELECTION: ")
            if type_of_week_cal not in ["1", "2", "3", "4"]:
                print("Not a valid selection")
            else:
                break
        if type_of_week_cal == "1":
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract week number from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col].dt.isocalendar().week
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        elif type_of_week_cal == "2":
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract week day num from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col].dt.weekday
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        elif type_of_week_cal == "3":
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract week day abbv. from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col].dt.strftime("%a")
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        else:
            print(" ")
            try:
                date_col = input("please enter the date column you want to extract week day full from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col].dt.day_name()
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
                
    def Day_Cal(self):
        print("\n")
        print("DAY CALCULATION")
        print("----")
        print("please select the type of day calculation you want perform")
        while True:
            type_of_day_cal = input("Day month(eg. 1-31): 1, Day Year(eg.1-365): 2; ⇛ SELECTION: ")
            if type_of_day_cal not in ["1", "2"]:
                print("Not a valid selection")
            else:
                break
        print(" ")
        if type_of_day_cal == "1":
            try: 
                date_col = input("please enter the date column you want to extract day from; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col].dt.day
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        else:
           try:
               date_col = input("please enter the date column you want to extract day from; ⇛ SELECTION: ")
               new_col = input("please enter the new column name; ⇛ SELECTION: ")
               self.table_name[new_col] = self.table_name[date_col].dt.dayofyear
               print(f"Column: {new_col} is added")
           except Exception as exe:
               print("Invalid Date Column or Table Name")
               print("Error:", exe)
               return 
        

    def DateDiff_Cal(self):
        print("\n")
        print("DATE DIFF CALCULATION")
        print("----")
        print("do you have a date column you want to subtract from. please choose from selection")
        while True:
            date_subtrate = input("you have a date column: 1, default(today date): 2; ⇛ SELECTION: ")
            if date_subtrate not in ["1", "2"]:
                print("please select from range")
            else:
                break
        print(" ")
        if date_subtrate == "1":
            print("please enter interval")
            while True:
                interval = input("Years: 1, Months: 2, Days: 3; ⇛ SELECTION: ")
                if interval not in ["1", "2", "3"]:
                    print("please enter from range")
                else:
                    break
            print(" ")
            if interval == "1":
                try:
                    date_col = input("please enter the data column(start date); ⇛ SELECTION: ")
                    date_col_substrat = input("please enter the date column you want to substract from(end date); ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = ((self.table_name[date_col_substrat] - self.table_name[date_col]).dt.days//365)
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
    
            
            elif interval == "2":
                try:
                    date_col = input("please enter the data column(start date); ⇛ SELECTION: ")
                    date_col_substrat = input("please enter the date column you want to substrat from(end date); ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = ((self.table_name[date_col_substrat] - self.table_name[date_col]).dt.days//30)
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
            else:
                try:
                    date_col = input("please enter the data column(start date); ⇛ SELECTION: ")
                    date_col_substrat = input("please enter the date column you want to substrat from(end date); ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = (self.table_name[date_col_substrat] - self.table_name[date_col]).dt.days
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
                    
        
        else:
            today = pd.Timestamp.today()
            print("please enter interval")
            while True:
                interval = input("Years: 1, Months: 2, Days: 3; ⇛ SELECTION: ")
                if interval not in ["1", "2", "3"]:
                    print("please enter from range")
                else:
                    break
            print(" ")
            if interval == "1":
                try:
                    date_col = input("please enter the data column(start date); ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = ((today - self.table_name[date_col]).dt.days//365)
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
            elif interval == "2":
                try:
                    date_col = input("please enter the data column(start date); ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = ((today - self.table_name[date_col]).dt.days//30)
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
            else:
                try:
                    date_col = input("please enter the data column(start date); ⇛ SELECTION: ")
                    new_col = input("please enter the new column name; ⇛ SELECTION: ")
                    self.table_name[new_col] = (today - self.table_name[date_col]).dt.days
                    print(f"Column: {new_col} is added")
                except Exception as exe:
                    print("Invalid Date Column or Table Name")
                    print("Error:", exe)
                    return
                    
    def DateAdd_Cal(self):
        print("\n")
        print("DATE ADD CALCULATION")
        print("----")
        print("please select what date addition you want to perform")
        while True:
            type_of_date_add = input("days: 1, weeks: 2, months: 3, years: 4, business days: 5; ⇛ SELECTION: ")
            if type_of_date_add not in ["1", "2", "3", "4", "5"]:
                print("please select from range")
            else:
                break
        print(" ")
        if type_of_date_add == "1":
            while True:
                try:
                    days_add = int(input("Enter the number of days you want to add; ⇛ SELECTION: "))
                    break
                except ValueError:
                    print("This is not an integer value")
            print(" ")
            try:
                date_col = input("Please enter the data column; ⇛ SELECTION: ")
                new_col = input("Please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col] + pd.DateOffset(days = days_add)
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        elif type_of_date_add == "2":
            while True:
                try:
                    weeks_add = int(input("Enter the number of weeks you want to add; ⇛ SELECTION: "))
                    break
                except ValueError:
                    print("This is not an integer value")
            print(" ")
            try:
                date_col = input("please enter the data column; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col] + pd.DateOffset(weeks = weeks_add)
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        elif type_of_date_add == "3":
            while True:
                try:
                    months_add = int(input("Enter the number of months you want to add; ⇛ SELECTION: "))
                    break
                except ValueError:
                    print("This is not an integer value")
            print(" ")
            try:
                date_col = input("please enter the data column; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col] + pd.DateOffset(months = months_add)
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        elif type_of_date_add == "4":
            while True:
                try:
                    years_add = int(input("Enter the number of years you want to add; ⇛ SELECTION: "))
                    break
                except ValueError:
                    print("This is not an integer value")
            print(" ")
            try:
                date_col = input("please enter the data column; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col] + pd.DateOffset(years = years_add)
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return
        else:
            while True:
                try:
                    business_days_add = int(input("Enter the number of business days you want to add; ⇛ SELECTION: "))
                    break
                except ValueError:
                    print("This is not an integer value")
            print(" ")
            try:
                date_col = input("please enter the data column; ⇛ SELECTION: ")
                new_col = input("please enter the new column name; ⇛ SELECTION: ")
                self.table_name[new_col] = self.table_name[date_col] + pd.offsets.BusinessDay(business_days_add)
                print(f"Column: {new_col} is added")
            except Exception as exe:
                print("Invalid Date Column or Table Name")
                print("Error:", exe)
                return

In [3]:
import pandas as pd

In [4]:
# IMPORTING THE DATE CSV FILE
df = pd.read_csv("Date learning.csv")
df.head()

       Date
0  1/1/2025
1  1/2/2025
2  1/3/2025
3  1/4/2025
4  1/5/2025

In [8]:
# CONVERTING THE DATE COLUMN OBJECT TO DATE

df["Date"] = pd.to_datetime(df["Date"], format = "%m/%d/%Y")

In [9]:
# ADDUNG YEAR COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  1

YEAR CALCULATION
----

please enter the date column you want to extract year from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Year

Column: Year is added

In [10]:
# ADDING QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  1

please enter the date column you want to extract quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Quater

Column: Quater is added

In [11]:
# ADDING START OF CURRENT QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  2

please enter the type of start of quarter you want to calculate

Start of Current Quarter: 0, Start of Next Quarter: 1, Start of Previous Quarter: -1; ⇛ SELECTION:  0

please enter the date column you want to extract start of quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Start of cur. Quarter

Column: Start of cur. Quarter is added

In [12]:
# ADDING START OF Next QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  2

please enter the type of start of quarter you want to calculate

Start of Current Quarter: 0, Start of Next Quarter: 1, Start of Previous Quarter: -1; ⇛ SELECTION:  1

please enter the date column you want to extract start of quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Start of nx. Quarter

Column: Start of nx. Quarter is added

In [13]:
# ADDING START OF PREVIOUS QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  2

please enter the type of start of quarter you want to calculate

Start of Current Quarter: 0, Start of Next Quarter: 1, Start of Previous Quarter: -1; ⇛ SELECTION:  -1

please enter the date column you want to extract start of quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Sart of pre. Quarter

Column: Sart of pre. Quarter is added

In [14]:
# ADDING END OF CURRENT QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  3

please enter the type of end of quarter you want to calculate

end of current quater: 0, end of next quarter: 1, end of previous quarter: -1; ⇛ SELECTION:  0

please enter the date column you want to extract end of quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  End of cur. Quarter

Column: End of cur. Quarter is added

In [15]:
# ADDING END OF NEXT QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  3

please enter the type of end of quarter you want to calculate

end of current quater: 0, end of next quarter: 1, end of previous quarter: -1; ⇛ SELECTION:  1

please enter the date column you want to extract end of quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  End of nx. Quarter

Column: End of nx. Quarter is added

In [16]:
# ADDING END OF PREVIOUS QUARTER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  2

QUARTER CALCULATION
----
please select what type of quarter calculation you want to perform

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  -1

This is not the range for quarter calculation

Quarter: 1, Start of Quarter: 2, End of Quarter: 3; ⇛ SELECTION:  3

please enter the type of end of quarter you want to calculate

end of current quater: 0, end of next quarter: 1, end of previous quarter: -1; ⇛ SELECTION:  -1

please enter the date column you want to extract end of quarter from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  End of pre. Quarter

Column: End of pre. Quarter is added

In [17]:
# ADDING MONTH NUMBER COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  1

please select from range what month calculation you want

Month Number(eg. 01): 1, Month Name abbv.(eg. Jan): 2, Month Name full(eg. January): 3; ⇛ SELECTION:  1

please enter the date column you want to extract month number from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Month Num

Column: Month Num is added

In [18]:
# ADDING MONTH NAME ABBV. COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  1

please select from range what month calculation you want

Month Number(eg. 01): 1, Month Name abbv.(eg. Jan): 2, Month Name full(eg. January): 3; ⇛ SELECTION:  2

please enter the date column you want to extract month name abbv. from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Month Name abbv.

Column: Month Name abbv. is added

In [19]:
# ADDING MONTH NAME FULL COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  1

please select from range what month calculation you want

Month Number(eg. 01): 1, Month Name abbv.(eg. Jan): 2, Month Name full(eg. January): 3; ⇛ SELECTION:  3

please enter the date column you want to extract month name full from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Month Name Full

Column: Month Name Full is added

In [25]:
# ADDING MONTH YEAR ABBV COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  2

please select from range what month year calculation you want

month year abbv. (eg. jan-2025): 1, month year full (eg. January-2025): 2; ⇛ SELECTION:  1

please enter the date column you want to extract month year abbv. from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Month Year abbv

Column: Month Year abbv is added

In [26]:
# ADDING MONTH YEAR FULL COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  2

please select from range what month year calculation you want

month year abbv. (eg. jan-2025): 1, month year full (eg. January-2025): 2; ⇛ SELECTION:  2

please enter the date column you want to extract month year full from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Month Year Full

Column: Month Year Full is added

In [27]:
# ADDING START OF CURRENT MONTH COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  3

please select what start of month calculated column you want

Start of Current Month: 0, Start of Next Month: 1, Start of Previous Month: -1; ⇛ SELECTION:  0

please enter the date column you want to extract start of month from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Start of cur. Month

Column: Start of cur. Month is added

In [28]:
# ADDING START OF NEXT MONTH COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  3

please select what start of month calculated column you want

Start of Current Month: 0, Start of Next Month: 1, Start of Previous Month: -1; ⇛ SELECTION:  1

please enter the date column you want to extract start of month from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Start of nx. Month

Column: Start of nx. Month is added

In [29]:
# ADDING START OF PREVIOUS MONTH COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  3

please select what start of month calculated column you want

Start of Current Month: 0, Start of Next Month: 1, Start of Previous Month: -1; ⇛ SELECTION:  -1

please enter the date column you want to extract start of month from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Start of pre. Month

Column: Start of pre. Month is added

In [30]:
# ADDING END OF CURRENT MONTH COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  4

please select what end of month calculated column you want

End of Current Month: 0, End of Next Month: 1, End of Previous Month: -1; ⇛ SELECTION:  0

please enter the date column you want to extract end of month from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  End of cur. Month

Column: End of cur. Month is added

In [31]:
# ADDING END OF NEXT MONTH COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  4

please select what end of month calculated column you want

End of Current Month: 0, End of Next Month: 1, End of Previous Month: -1; ⇛ SELECTION:  1

please enter the date column you want to extract end of month from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  End of nx. Month

Column: End of nx. Month is added

In [32]:
# ADDING END OF PREVIOUS MONTH COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  3

MONTH CALCULATION
----
please select the type of month calculation you want perform

Month: 1, Month Year: 2, Start of Month: 3, End of Month: 4; ⇛ SELECTION:  4

please select what end of month calculated column you want

End of Current Month: 0, End of Next Month: 1, End of Previous Month: -1; ⇛ SELECTION:  -1

please enter the date column you want to extract end of month from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  End of pre. Month

Column: End of pre. Month is added

In [34]:
# ADDING WEEK NUM COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  4

WEEK CALCULATION
----
please select the type of week calculation you want perform

Week Number(eg. 52): 1, WeekDay Number(eg. 3) : 2, WeekDay Name abbv.(eg. wed): 3, WeekDay Name full.(eg. wednesday): 4; ⇛ SELECTION:  1

please enter the date column you want to extract week number from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Week Num

Column: Week Num is added

In [35]:
# ADDING WEEKDAY NUM COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  4

WEEK CALCULATION
----
please select the type of week calculation you want perform

Week Number(eg. 52): 1, WeekDay Number(eg. 3) : 2, WeekDay Name abbv.(eg. wed): 3, WeekDay Name full.(eg. wednesday): 4; ⇛ SELECTION:  2

please enter the date column you want to extract week day num from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  WeekDay Num

Column: WeekDay Num is added

In [36]:
# ADDING WEEK DAY NAME COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  4

WEEK CALCULATION
----
please select the type of week calculation you want perform

Week Number(eg. 52): 1, WeekDay Number(eg. 3) : 2, WeekDay Name abbv.(eg. wed): 3, WeekDay Name full.(eg. wednesday): 4; ⇛ SELECTION:  3

please enter the date column you want to extract week day abbv. from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  WeekDay Name abbv.

Column: WeekDay Name abbv. is added

In [37]:
# ADDING WEEK NUM COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  4

WEEK CALCULATION
----
please select the type of week calculation you want perform

Week Number(eg. 52): 1, WeekDay Number(eg. 3) : 2, WeekDay Name abbv.(eg. wed): 3, WeekDay Name full.(eg. wednesday): 4; ⇛ SELECTION:  4

please enter the date column you want to extract week day full from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  WeekDay Name Full

Column: WeekDay Name Full is added

In [39]:
# ADDING DAY COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  5

DAY CALCULATION
----
please select the type of day calculation you want perform

Day month(eg. 1-31): 1, Day Year(eg.1-365): 2; ⇛ SELECTION:  1

please enter the date column you want to extract day from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Day

Column: Day is added

In [40]:
# ADDING DAY YEAR COLUMN
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  5

DAY CALCULATION
----
please select the type of day calculation you want perform

Day month(eg. 1-31): 1, Day Year(eg.1-365): 2; ⇛ SELECTION:  2

please enter the date column you want to extract day from; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Day Year

Column: Day Year is added

In [41]:
# ADDING DATE DIFF IN YEARS
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  6

DATE DIFF CALCULATION
----
do you have a date column you want to subtract from. please choose from selection

you have a date column: 1, default(today date): 2; ⇛ SELECTION:  2

please enter interval

Years: 1, Months: 2, Days: 3; ⇛ SELECTION:  1

please enter the data column(start date); ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Date Diff Year

Column: Date Diff Year is added

In [43]:
# ADDING DATE DIFF IN MONTHS
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  6

DATE DIFF CALCULATION
----
do you have a date column you want to subtract from. please choose from selection

you have a date column: 1, default(today date): 2; ⇛ SELECTION:  2

please enter interval

Years: 1, Months: 2, Days: 3; ⇛ SELECTION:  2

please enter the data column(start date); ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Date Diff Month

Column: Date Diff Month is added

In [44]:
# ADDING DATE DIFF IN DAYS
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  6

DATE DIFF CALCULATION
----
do you have a date column you want to subtract from. please choose from selection

you have a date column: 1, default(today date): 2; ⇛ SELECTION:  2

please enter interval

Years: 1, Months: 2, Days: 3; ⇛ SELECTION:  3

please enter the data column(start date); ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Date Diff Days

Column: Date Diff Days is added

In [46]:
# ADDING DATE ADD IN DAYS(10 DAYS)
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  7

DATE ADD CALCULATION
----
please select what date addition you want to perform

days: 1, weeks: 2, months: 3, years: 4, business days: 5; ⇛ SELECTION:  1

Enter the number of days you want to add; ⇛ SELECTION:  10

Please enter the data column; ⇛ SELECTION:  Date
Please enter the new column name; ⇛ SELECTION:  Date Add Days

Column: Date Add Days is added

In [47]:
# ADDING DATE ADD IN WEEKS(15 WEEKS)
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  7

DATE ADD CALCULATION
----
please select what date addition you want to perform

days: 1, weeks: 2, months: 3, years: 4, business days: 5; ⇛ SELECTION:  2

Enter the number of weeks you want to add; ⇛ SELECTION:  15

please enter the data column; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Days Add Weeks

Column: Days Add Weeks is added

In [48]:
# ADDING DATE ADD IN Month (2 MONTH)
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  7

DATE ADD CALCULATION
----
please select what date addition you want to perform

days: 1, weeks: 2, months: 3, years: 4, business days: 5; ⇛ SELECTION:  3

Enter the number of months you want to add; ⇛ SELECTION:  2

please enter the data column; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Date Add Months

Column: Date Add Months is added

In [49]:
# ADDING DATE ADD IN Years(4 YEARS)
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  7

DATE ADD CALCULATION
----
please select what date addition you want to perform

days: 1, weeks: 2, months: 3, years: 4, business days: 5; ⇛ SELECTION:  4

Enter the number of years you want to add; ⇛ SELECTION:  4

please enter the data column; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Date Add Years

Column: Date Add Years is added

In [50]:
# ADDING DATE ADD IN BUSINESS DAYS(4 BUSINESS DAYS)
date_table = Calculate_Date(df)

DATE TABLE
----
Please select the date calculation you want from range

Year: 1, Quarter: 2, Month: 3, Week: 4, Day: 5, Date diff: 6, Date add: 7 (cancel calculation: 8); ⇛ SELECTION:  7

DATE ADD CALCULATION
----
please select what date addition you want to perform

days: 1, weeks: 2, months: 3, years: 4, business days: 5; ⇛ SELECTION:  5

Enter the number of business days you want to add; ⇛ SELECTION:  4

please enter the data column; ⇛ SELECTION:  Date
please enter the new column name; ⇛ SELECTION:  Date Add Bus.Days

Column: Date Add Bus.Days is added

In [22]:
pd.set_option("display.max_columns", None)

In [51]:
df.head()

,Date,Year,Quater,Start of cur. Quarter,Start of nx. Quarter,Sart of pre. Quarter,End of cur. Quarter,End of nx. Quarter,End of pre. Quarter,Month Num,Month Name abbv.,Month Name Full,Month Year abbv,Month Year Full,Start of cur. Month,Start of nx. Month,Start of pre. Month,End of cur. Month,End of nx. Month,End of pre. Month,Week Num,WeekDay Num,WeekDay Name abbv.,WeekDay Name Full,Day,Day Year,Date Diff Year,Date Diff Month,Date Diff Days,Date Add Days,Days Add Weeks,Date Add Months,Date Add Years,Date Add Bus.Days
0,2025-01-01,2025,1,2025-01-01,2025-04-01,2024-10-01,2025-03-31,2025-06-30,2024-12-31,1,Jan,January,Jan-2025,January-2025,2025-01-01,2025-02-01,2024-12-01,2025-01-31,2025-02-28,2024-12-31,1,2,Wed,Wednesday,1,1,0,10,308,2025-01-11,2025-04-16,2025-03-01,2029-01-01,2025-01-07
1,2025-01-02,2025,1,2025-01-01,2025-04-01,2024-10-01,2025-03-31,2025-06-30,2024-12-31,1,Jan,January,Jan-2025,January-2025,2025-01-01,2025-02-01,2024-12-01,2025-01-31,2025-02-28,2024-12-31,1,3,Thu,Thursday,2,2,0,10,307,2025-01-12,2025-04-17,2025-03-02,2029-01-02,2025-01-08
2,2025-01-03,2025,1,2025-01-01,2025-04-01,2024-10-01,2025-03-31,2025-06-30,2024-12-31,1,Jan,January,Jan-2025,January-2025,2025-01-01,2025-02-01,2024-12-01,2025-01-31,2025-02-28,2024-12-31,1,4,Fri,Friday,3,3,0,10,306,2025-01-13,2025-04-18,2025-03-03,2029-01-03,2025-01-09
3,2025-01-04,2025,1,2025-01-01,2025-04-01,2024-10-01,2025-03-31,2025-06-30,2024-12-31,1,Jan,January,Jan-2025,January-2025,2025-01-01,2025-02-01,2024-12-01,2025-01-31,2025-02-28,2024-12-31,1,5,Sat,Saturday,4,4,0,10,305,2025-01-14,2025-04-19,2025-03-04,2029-01-04,2025-01-09
4,2025-01-05,2025,1,2025-01-01,2025-04-01,2024-10-01,2025-03-31,2025-06-30,2024-12-31,1,Jan,January,Jan-2025,January-2025,2025-01-01,2025-02-01,2024-12-01,2025-01-31,2025-02-28,2024-12-31,1,6,Sun,Sunday,5,5,0,10,304,2025-01-15,2025-04-20,2025-03-05,2029-01-05,2025-01-09

In [52]:
#creating a csv files from the result date table
df.to_csv("Date Table.csv", index = False)